### ISSUE TITLE
Typo on variable name

### ISSUE THREAD

**Issue by mmartinortiz** [CurrySoftware/Telegram-Notifier#1]
Hi,

There is a typo on the variable name `TELEGRAM_KEY`, it is called TELEGR**E**M_KEY. I also wonder if the variable should not be called `BOT_TOKEN`.

https://github.com/CurrySoftware/Telegram-Notifier/blob/0f090326c6dc8c13cf939f10072dd6eb9247e599/etc/telegram/key.sh#L1

**Comment by JDemler** [comment]
Thanks.
Fixed in a20fed1
